### ISSUE TITLE
Not able to Publish or Subscribe to ROS

### ISSUE THREAD

**Issue by thejeshk** [tud-cor/FS19_modROS#11]
Hi, 

Thanks for great repo [Farmsim 19 with ROS]. 

I tried following: 
1. Install FarmSim 19 [Windows 10]
2. Installed modROS 

When I try to "rosPubMsg = True" I am getting error: Could not find named Pipe: Unknown reason (FS Lua does not seem to provide it]

Errors: 
![Screenshot (3)](https://user-images.githubusercontent.com/33362523/120165225-a559a600-c1fb-11eb-9df1-e98a29bf676f.png)

 Folder struct: 
![modROS_folder_2snap](https://user-images.githubusercontent.com/33362523/120165895-5102f600-c1fc-11eb-92f8-34159a8e320c.JPG)
![modROS_folder_snap](https://user-images.githubusercontent.com/33362523/120165897-519b8c80-c1fc-11eb-8189-9709b748711c.JPG)

Symbolic_link : Created
![symbolic_link_snap](https://user-images.githubusercontent.com/33362523/120165945-60823f00-c1fc-11eb-8be0-abafcbf3252e.JPG)

Please let me know what am I missing?

**Comment by thejeshk** [comment]
```

(venv_modROS) C:\Users\Thejesh\Desktop\fs_mod_ros_windows\nodes>python all_in_one_publisher.py
symbolic link has already been created
WARNING: cannot load logging configuration file, logging is disabled
Unable to immediately register with master node [http://localhost:11311/]: master may not be running yet. Will keep tryi
Unable to immediately register with master node [http://localhost:11311/]: master may not be running yet. Will keep tryi
Unable to immediately register with master node [http://localhost:11311/]: master may not be running yet. Will keep tryi
Unable to immediately register with master node [http://localhost:11311/]: master may not be running yet. Will keep tryi
Unable to immediately register with master node [http://localhost:11311/]: master may not be running yet. Will keep trying.
Traceback (most recent call last):
  File "C:\Users\Thejesh\PycharmProjects\pythonProject\venv_modROS\lib\site-packages\rospy\impl\registration.py", line 375, in cleanup
    multi()
  File "C:\Users\Thejesh\AppData\Local\Programs\Python\Python38\lib\xmlrpc\client.py", line 879, in __call__
    return MultiCallIterator(self.__server.system.multicall(marshalled_list))
  File "C:\Users\Thejesh\AppData\Local\Programs\Python\Python38\lib\xmlrpc\client.py", line 1109, in __call__
    return self.__send(self.__name, args)
  File "C:\Users\Thejesh\PycharmProjects\pythonProject\venv_modROS\lib\site-packages\rospy\core.py", line 665, in _ServerProxy__request
    return xmlrpcclient.ServerProxy._ServerProxy__request(
  File "C:\Users\Thejesh\AppData\Local\Programs\Python\Python38\lib\xmlrpc\client.py", line 1450, in __request
    response = self.__transport.request(
  File "C:\Users\Thejesh\AppData\Local\Programs\Python\Python38\lib\xmlrpc\client.py", line 1153, in request
    return self.single_request(host, handler, request_body, verbose)
  File "C:\Users\Thejesh\AppData\Local\Programs\Python\Python38\lib\xmlrpc\client.py", line 1165, in single_request
    http_conn = self.send_request(host, handler, request_body, verbose)
  File "C:\Users\Thejesh\AppData\Local\Programs\Python\Python38\lib\xmlrpc\client.py", line 1278, in send_request
    self.send_content(connection, request_body)
  File "C:\Users\Thejesh\AppData\Local\Programs\Python\Python38\lib\xmlrpc\client.py", line 1308, in send_content
    connection.endheaders(request_body)
  File "C:\Users\Thejesh\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\Thejesh\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1010, in _send_output
    self.send(msg)
  File "C:\Users\Thejesh\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 950, in send
    self.connect()
  File "C:\Users\Thejesh\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 921, in connect
    self.sock = self._create_connection(
  File "C:\Users\Thejesh\AppData\Local\Programs\Python\Python38\lib\socket.py", line 808, in create_connection
    raise err
  File "C:\Users\Thejesh\AppData\Local\Programs\Python\Python38\lib\socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Thejesh\PycharmProjects\pythonProject\venv_modROS\lib\site-packages\rospy\core.py", line 575, in signal_shutdown
    h(reason)
  File "C:\Users\Thejesh\PycharmProjects\pythonProject\venv_modROS\lib\site-packages\rospy\impl\registration.py", line 377, in cleanup
    (se_errno, msg) = se.args
ValueError: too many values to unpack (expected 2)
Traceback (most recent call last):
  File "all_in_one_publisher.py", line 138, in <module>
    rospy.init_node('ros_publisher', anonymous=True)
  File "C:\Users\Thejesh\PycharmProjects\pythonProject\venv_modROS\lib\site-packages\rospy\client.py", line 323, in init_node
    raise rospy.exceptions.ROSInitException("init_node interrupted before it could complete")
rospy.exceptions.ROSInitException: init_node interrupted before it could complete

```

**Comment by gavanderhoorn** [comment]
I believe the order of commands needed is perhaps unclear.

As the readme states (in the [Running](https://github.com/tud-cor/FS19_modROS/tree/642ddf9c7fbbcb6ad53aea7ad8f8e52b80050c29#running) section):

> Note: Before proceeding to the next step, make sure you see waiting for client from FarmSim19 in the cmd window

the errors in the FS prompt are to be expected I believe if you haven't started `all_in_one_publisher.py` yet.

The errors from `all_in_one_publisher.py` you show seem to be due to not having correctly configured the required environment variables (ie: `ROS_IP` and `ROS_MASTER_URI`). This is the same configuration needed for a regular ROS 1 installation when using multiple hosts.

@tckarenchiang: we should consider updating the documentation to add some information on that.

@thejeshk: for now, refer to [General Usage](https://github.com/tud-cor/d3dshot_screen_grabber/tree/6d64168838a8871588d1f4d45dd97d854214a405#general-usage) in the `d3dshot_screen_grabber` readme. This does not use `ROS_IP` or `ROS_MASTER_URI` environment variables, but passes them directly to the script as arguments.

Something like this should work:

```
python path\to\all_in_one_publisher.py __ip:=<ip of this PC> __master:=http://<ip of the PC running roscore>:11311
```

Note: there is no point in trying to continue with the next step in the documentation until you can successfully run the `.py` scripts.

**Comment by gavanderhoorn** [comment]
@thejeshk: were you able to get things to work?

**Comment by gavanderhoorn** [comment]
I'm going to close, assuming the initial problems reported by the OP have been addressed/explained.

I've followed all instructions myself again and while there are some possible issues (such as #25), and the UX could be improved, we're tracking those or they are manageable.

@thejeshk: if you're still having difficulties getting things to work, comment here and we can see whether this needs to be re-opened.

**Comment by thejeshk** [comment]
Hi @gavanderhoorn 

Sorry! It's been a while now. I was not working with FarmSim for a while now because my personal PC had some issues. 

recently, I joined as a researcher at JD and will be working with Farmsim 22. after setting up everythin (ROS, Farmsim, etc ), I would update this thread of how this integration goes! 

Thank you 
TK

**Comment by gavanderhoorn** [comment]
Just to clarify: we've developed `modROS` for FS19. I'm not sure newer versions will work.

But we're interested to hear about your experiences.
